"""Paybond Kit — hosted Gateway clients, evidence signing, service-account sessions, and agent framework hooks."""

from __future__ import annotations

from paybond_kit.agent_adapters import paybond_runtime_tool_call_adapter
from paybond_kit.capability_binding import PaybondCapabilityBinding
from paybond_kit.credentials import (
    DEFAULT_PAYBOND_GATEWAY_BASE_URL,
    GatewayAuthError,
    InsecureGatewayURLError,
    PaybondEnvironment,
    is_local_gateway_host,
    normalize_gateway_base_url,
)
from paybond_kit.a2a import A2AHttpError, GatewayA2AClient
from paybond_kit.fraud import (
    FraudHttpError,
    GatewayFraudClient,
    ServiceAccountFraudSession,
    SignalFraudAssessment,
    SignalFraudAssessmentResponse,
    SignalFraudMetricsResponse,
    SignalFraudReviewEventInput,
    SignalFraudReviewEventResponse,
    SignalFraudReviewQueueItem,
    SignalFraudReviewQueueResponse,
    SignalFraudSignal,
)
from paybond_kit.guardrails import (
    GatewaySandboxGuardrailsClient,
    SandboxGuardrailBootstrapResult,
    SandboxGuardrailEvidenceResult,
)
from paybond_kit.harbor import (
    FundIntentResult,
    GatewayHarborClient,
    HarborClient,
    HarborHttpError,
    IntentFundingResult,
    SettlementRail,
    TenantBindingError,
    VerifyCapabilityResult,
)
from paybond_kit.audit.exports import PaybondAudit, PaybondAuditExports
from paybond_kit.paybond import Paybond, PaybondIntents
from paybond_kit.protocol import (
    AgentRecognitionProofV1,
    AgentMandateV1,
    GatewayProtocolClient,
    ImportAgentMandateV1Result,
    ProtocolAuthorizationReceiptV1,
    ProtocolHttpError,
    ProtocolSettlementReceiptV1,
    ProtocolTransportBindingV1,
    SignedAgentMandateV1,
    VerifyProtocolReceiptV1Result,
)
from paybond_kit.signal import (
    GatewaySignalClient,
    ServiceAccountSignalSession,
    SignalHttpError,
    SignalPortfolioSummary,
    SignalReceiptEnvelope,
    SignalSignedPortfolioArtifact,
    SignalSignedReceipt,
)
from paybond_kit.x402_funding import (
    FundRequestEnvelope,
    PaybondX402FundingFailedError,
    PaybondX402FundingPendingError,
    X402FundPollOptions,
    build_x402_fund_request_envelope,
    execute_fund_with_x402,
)
from paybond_kit.mpp_funding import (
    MppFundPollOptions,
    ParsedPaymentAuthChallenge,
    PaybondMppFundingFailedError,
    PaybondMppFundingPendingError,
    build_mpp_fund_request_envelope,
    execute_fund_with_mpp,
    execute_fund_with_mpp_charge,
    execute_fund_with_mpp_session,
    parse_payment_auth_challenge,
    select_mpp_charge_challenge,
    select_mpp_session_challenge,
)
from paybond_kit.payment_transport import (
    PAYBOND_PAYMENT_AUTHORIZATION_HEADER,
    PAYMENT_TRANSPORT_RESPONSE_HEADERS,
    format_payment_authorization_value,
    payment_authorization_gateway_header,
    read_fund_payment_transport_headers,
)
from paybond_kit.spend_guard import (
    PaybondSpendDeniedError,
    PaybondSpendApprovalRequiredError,
    PaybondSpendGuard,
    authorize_spend,
    guard_tool,
    paybond_agent_tool_spend_guard,
    paybond_langgraph_tool_spend_guard,
    paybond_mcp_tool_spend_guard,
    paybond_runtime_neutral_tool_spend_guard,
)

__all__ = [
    "A2AHttpError",
    "DEFAULT_PAYBOND_GATEWAY_BASE_URL",
    "GatewayAuthError",
    "InsecureGatewayURLError",
    "GatewayA2AClient",
    "GatewayFraudClient",
    "GatewayHarborClient",
    "GatewayProtocolClient",
    "GatewaySandboxGuardrailsClient",
    "FundIntentResult",
    "HarborClient",
    "HarborHttpError",
    "IntentFundingResult",
    "SettlementRail",
    "PaybondEnvironment",
    "is_local_gateway_host",
    "normalize_gateway_base_url",
    "Paybond",
    "PaybondAudit",
    "PaybondAuditExports",
    "PaybondCapabilityBinding",
    "PaybondIntents",
    "PaybondX402FundingFailedError",
    "PaybondX402FundingPendingError",
    "FundRequestEnvelope",
    "X402FundPollOptions",
    "build_x402_fund_request_envelope",
    "execute_fund_with_x402",
    "PaybondMppFundingFailedError",
    "PaybondMppFundingPendingError",
    "MppFundPollOptions",
    "ParsedPaymentAuthChallenge",
    "build_mpp_fund_request_envelope",
    "execute_fund_with_mpp",
    "execute_fund_with_mpp_charge",
    "execute_fund_with_mpp_session",
    "parse_payment_auth_challenge",
    "select_mpp_charge_challenge",
    "select_mpp_session_challenge",
    "PaybondSpendDeniedError",
    "PaybondSpendApprovalRequiredError",
    "PaybondSpendGuard",
    "SandboxGuardrailBootstrapResult",
    "SandboxGuardrailEvidenceResult",
    "GatewaySignalClient",
    "FraudHttpError",
    "ServiceAccountFraudSession",
    "ServiceAccountSignalSession",
    "SignalFraudAssessment",
    "SignalFraudAssessmentResponse",
    "SignalFraudMetricsResponse",
    "SignalFraudReviewEventInput",
    "SignalFraudReviewEventResponse",
    "SignalFraudReviewQueueItem",
    "SignalFraudReviewQueueResponse",
    "SignalFraudSignal",
    "SignalHttpError",
    "SignalPortfolioSummary",
    "SignalReceiptEnvelope",
    "SignalSignedPortfolioArtifact",
    "SignalSignedReceipt",
    "ProtocolHttpError",
    "AgentRecognitionProofV1",
    "AgentMandateV1",
    "SignedAgentMandateV1",
    "ProtocolTransportBindingV1",
    "ProtocolAuthorizationReceiptV1",
    "ProtocolSettlementReceiptV1",
    "ImportAgentMandateV1Result",
    "VerifyProtocolReceiptV1Result",
    "TenantBindingError",
    "VerifyCapabilityResult",
    "PAYBOND_PAYMENT_AUTHORIZATION_HEADER",
    "PAYMENT_TRANSPORT_RESPONSE_HEADERS",
    "format_payment_authorization_value",
    "payment_authorization_gateway_header",
    "read_fund_payment_transport_headers",
    "authorize_spend",
    "guard_tool",
    "paybond_agent_tool_spend_guard",
    "paybond_langgraph_tool_spend_guard",
    "paybond_mcp_tool_spend_guard",
    "paybond_runtime_neutral_tool_spend_guard",
    "paybond_runtime_tool_call_adapter",
    "sign_payee_evidence_binding",
]
