"""Paybond Kit — hosted Gateway clients, evidence signing, service-account sessions, and agent framework hooks."""

from __future__ import annotations

from paybond_kit.agent_adapters import paybond_runtime_tool_call_adapter
from paybond_kit.capability_binding import PaybondCapabilityBinding
from paybond_kit.credentials import (
    DEFAULT_PAYBOND_GATEWAY_BASE_URL,
    GatewayAuthError,
    InsecureGatewayURLError,
    PaybondEnvironment,
    is_local_gateway_host,
    normalize_gateway_base_url,
)
from paybond_kit.a2a import A2AHttpError, GatewayA2AClient
from paybond_kit.fraud import (
    FraudHttpError,
    GatewayFraudClient,
    ServiceAccountFraudSession,
    SignalFraudAssessment,
    SignalFraudAssessmentResponse,
    SignalFraudMetricsResponse,
    SignalFraudReviewEventInput,
    SignalFraudReviewEventResponse,
    SignalFraudReviewQueueItem,
    SignalFraudReviewQueueResponse,
    SignalFraudSignal,
)
from paybond_kit.guardrails import (
    GatewaySandboxGuardrailsClient,
    SandboxGuardrailBootstrapResult,
    SandboxGuardrailEvidenceResult,
)
from paybond_kit.harbor import (
    FundIntentResult,
    GatewayHarborClient,
    HarborClient,
    HarborHttpError,
    IntentFundingResult,
    SettlementRail,
    TenantBindingError,
    VerifyCapabilityResult,
)
from paybond_kit.audit.exports import PaybondAudit, PaybondAuditExports
from paybond_kit.paybond import Paybond, PaybondIntents

# Operator/backend-only Plaid bank helpers (H5). Intentionally absent from
# `paybond_kit.agent`, agent templates, and the MCP tool surface: operators link
# banks and fund intents; agents spend only on already funded intents.
from paybond_kit.plaid import (
    PLAID_READINESS_REASONS,
    OperatorPlaidBankClient,
    PlaidAchFundingResult,
    PlaidBankAccount,
    PlaidBankInventory,
    PlaidBankNotFoundError,
    PlaidBankNotReadyError,
    PlaidOperatorError,
    PlaidOperatorHttpError,
    PlaidSecretMaterialError,
    ServiceAccountPlaidSession,
    fund_ach_with_plaid_bank,
    list_plaid_banks,
    plaid_readiness_message,
)
from paybond_kit.protocol import (
    AgentRecognitionProofV1,
    AgentMandateV1,
    GatewayProtocolClient,
    ImportAgentMandateV1Result,
    ProtocolAuthorizationReceiptV1,
    ProtocolHttpError,
    ProtocolSettlementReceiptV1,
    ProtocolTransportBindingV1,
    SignedAgentMandateV1,
    VerifyProtocolReceiptV1Result,
)
from paybond_kit.signal import (
    GatewaySignalClient,
    ServiceAccountSignalSession,
    SignalHttpError,
    SignalPortfolioSummary,
    SignalReceiptEnvelope,
    SignalSignedPortfolioArtifact,
    SignalSignedReceipt,
)
from paybond_kit.x402_funding import (
    FundRequestEnvelope,
    PaybondX402FundingFailedError,
    PaybondX402FundingPendingError,
    X402FundPollOptions,
    build_x402_fund_request_envelope,
    execute_fund_with_x402,
)
from paybond_kit.mpp_funding import (
    MppFundPollOptions,
    ParsedPaymentAuthChallenge,
    PaybondMppFundingFailedError,
    PaybondMppFundingPendingError,
    build_mpp_fund_request_envelope,
    execute_fund_with_mpp,
    execute_fund_with_mpp_charge,
    execute_fund_with_mpp_session,
    parse_payment_auth_challenge,
    select_mpp_charge_challenge,
    select_mpp_session_challenge,
)
from paybond_kit.stripe_commerce import (
    PAYBOND_STRIPE_METADATA_INTENT_ID_KEY,
    PAYBOND_STRIPE_METADATA_RAIL_KEY,
    PAYBOND_STRIPE_METADATA_TENANT_ID_KEY,
    STRIPE_COMMERCE_MAPPER_VERSION,
    assert_not_stripe_funding_webhook,
    build_paybond_stripe_metadata,
    map_stripe_tool_result_to_evidence,
)
from paybond_kit.commerce_binding import (
    PAYBOND_COMMERCE_BINDING_INTENT_ID_KEY,
    PAYBOND_COMMERCE_BINDING_TENANT_ID_KEY,
    decode_commerce_binding_from_shopify_note_attributes,
    decode_commerce_binding_from_stripe_metadata,
    encode_commerce_binding_to_shopify_note_attributes,
    encode_commerce_binding_to_stripe_metadata,
    normalize_commerce_binding,
)
from paybond_kit.shopify import (
    PAYBOND_SHOPIFY_UCP_VERSION,
    PAYBOND_UCP_AGENT_PROFILE_URL,
    SHOPIFY_COMMERCE_MAPPER_VERSION,
    assert_not_shopify_funding_webhook,
    create_checkout_with_binding,
    create_guarded_shopify_checkout_handler,
    get_order,
    instrument_shopify_checkout,
    map_shopify_tool_result_to_evidence,
    merge_binding_into_checkout_payload,
    to_ucp_checkout_line_items,
)
from paybond_kit.payment_transport import (
    PAYBOND_PAYMENT_AUTHORIZATION_HEADER,
    PAYMENT_TRANSPORT_RESPONSE_HEADERS,
    format_payment_authorization_value,
    payment_authorization_gateway_header,
    read_fund_payment_transport_headers,
)
from paybond_kit.spend_guard import (
    PaybondSpendDeniedError,
    PaybondSpendApprovalRequiredError,
    PaybondSpendGuard,
    authorize_spend,
    guard_tool,
    paybond_agent_tool_spend_guard,
    paybond_langgraph_tool_spend_guard,
    paybond_mcp_tool_spend_guard,
    paybond_runtime_neutral_tool_spend_guard,
)
from paybond_kit.signing import sign_payee_evidence_binding

__all__ = [
    "A2AHttpError",
    "DEFAULT_PAYBOND_GATEWAY_BASE_URL",
    "GatewayAuthError",
    "InsecureGatewayURLError",
    "GatewayA2AClient",
    "GatewayFraudClient",
    "GatewayHarborClient",
    "GatewayProtocolClient",
    "GatewaySandboxGuardrailsClient",
    "FundIntentResult",
    "HarborClient",
    "HarborHttpError",
    "IntentFundingResult",
    "SettlementRail",
    "PaybondEnvironment",
    "is_local_gateway_host",
    "normalize_gateway_base_url",
    "Paybond",
    "PaybondAudit",
    "PaybondAuditExports",
    "PaybondCapabilityBinding",
    "PaybondIntents",
    "PLAID_READINESS_REASONS",
    "OperatorPlaidBankClient",
    "PlaidAchFundingResult",
    "PlaidBankAccount",
    "PlaidBankInventory",
    "PlaidBankNotFoundError",
    "PlaidBankNotReadyError",
    "PlaidOperatorError",
    "PlaidOperatorHttpError",
    "PlaidSecretMaterialError",
    "ServiceAccountPlaidSession",
    "fund_ach_with_plaid_bank",
    "list_plaid_banks",
    "plaid_readiness_message",
    "PaybondX402FundingFailedError",
    "PaybondX402FundingPendingError",
    "FundRequestEnvelope",
    "X402FundPollOptions",
    "build_x402_fund_request_envelope",
    "execute_fund_with_x402",
    "PaybondMppFundingFailedError",
    "PaybondMppFundingPendingError",
    "MppFundPollOptions",
    "ParsedPaymentAuthChallenge",
    "build_mpp_fund_request_envelope",
    "execute_fund_with_mpp",
    "execute_fund_with_mpp_charge",
    "execute_fund_with_mpp_session",
    "parse_payment_auth_challenge",
    "select_mpp_charge_challenge",
    "select_mpp_session_challenge",
    "PAYBOND_STRIPE_METADATA_INTENT_ID_KEY",
    "PAYBOND_STRIPE_METADATA_RAIL_KEY",
    "PAYBOND_STRIPE_METADATA_TENANT_ID_KEY",
    "STRIPE_COMMERCE_MAPPER_VERSION",
    "assert_not_stripe_funding_webhook",
    "build_paybond_stripe_metadata",
    "map_stripe_tool_result_to_evidence",
    "PAYBOND_COMMERCE_BINDING_INTENT_ID_KEY",
    "PAYBOND_COMMERCE_BINDING_TENANT_ID_KEY",
    "decode_commerce_binding_from_shopify_note_attributes",
    "decode_commerce_binding_from_stripe_metadata",
    "encode_commerce_binding_to_shopify_note_attributes",
    "encode_commerce_binding_to_stripe_metadata",
    "normalize_commerce_binding",
    "PAYBOND_SHOPIFY_UCP_VERSION",
    "PAYBOND_UCP_AGENT_PROFILE_URL",
    "SHOPIFY_COMMERCE_MAPPER_VERSION",
    "assert_not_shopify_funding_webhook",
    "create_checkout_with_binding",
    "create_guarded_shopify_checkout_handler",
    "get_order",
    "instrument_shopify_checkout",
    "map_shopify_tool_result_to_evidence",
    "merge_binding_into_checkout_payload",
    "to_ucp_checkout_line_items",
    "PaybondSpendDeniedError",
    "PaybondSpendApprovalRequiredError",
    "PaybondSpendGuard",
    "SandboxGuardrailBootstrapResult",
    "SandboxGuardrailEvidenceResult",
    "GatewaySignalClient",
    "FraudHttpError",
    "ServiceAccountFraudSession",
    "ServiceAccountSignalSession",
    "SignalFraudAssessment",
    "SignalFraudAssessmentResponse",
    "SignalFraudMetricsResponse",
    "SignalFraudReviewEventInput",
    "SignalFraudReviewEventResponse",
    "SignalFraudReviewQueueItem",
    "SignalFraudReviewQueueResponse",
    "SignalFraudSignal",
    "SignalHttpError",
    "SignalPortfolioSummary",
    "SignalReceiptEnvelope",
    "SignalSignedPortfolioArtifact",
    "SignalSignedReceipt",
    "ProtocolHttpError",
    "AgentRecognitionProofV1",
    "AgentMandateV1",
    "SignedAgentMandateV1",
    "ProtocolTransportBindingV1",
    "ProtocolAuthorizationReceiptV1",
    "ProtocolSettlementReceiptV1",
    "ImportAgentMandateV1Result",
    "VerifyProtocolReceiptV1Result",
    "TenantBindingError",
    "VerifyCapabilityResult",
    "PAYBOND_PAYMENT_AUTHORIZATION_HEADER",
    "PAYMENT_TRANSPORT_RESPONSE_HEADERS",
    "format_payment_authorization_value",
    "payment_authorization_gateway_header",
    "read_fund_payment_transport_headers",
    "authorize_spend",
    "guard_tool",
    "paybond_agent_tool_spend_guard",
    "paybond_langgraph_tool_spend_guard",
    "paybond_mcp_tool_spend_guard",
    "paybond_runtime_neutral_tool_spend_guard",
    "paybond_runtime_tool_call_adapter",
    "sign_payee_evidence_binding",
]
