"""Model-agnostic agent middleware core (registry, run binding, interceptor)."""

from paybond_kit.agent.adapter import (
    create_generic_tool_executor,
    create_tool_input_guard_adapter,
    paybond_generic_tool_executor_adapter,
    paybond_tool_input_guard_adapter,
)
from paybond_kit.agent.facade import (
    PaybondAgentHooks,
    PaybondAgentResult,
    create_paybond_agent,
    instrument_paybond_agent,
    resolve_agent_policy_source,
    to_paybond_agent_result,
    wrap_paybond_tools,
)
from paybond_kit.agent.guarded_agent import (
    CreateGuardedAgentInput,
    CreateGuardedAgentResult,
    GuardedAgentFramework,
    create_guarded_agent,
    create_guarded_agent_runner,
)
from paybond_kit.agent.generic_runner import (
    PaybondGenericAgentConfig,
    create_paybond_generic_agent_config,
    create_paybond_generic_input_guard,
)
from paybond_kit.agent.interceptor import (
    AgentReceiptComposeResult,
    PaybondAutoEvidenceSubmitError,
    PaybondEvidenceSubmitError,
    PaybondInterceptEvidenceResult,
    PaybondInterceptWrapExecuteResult,
    PaybondToolInterceptor,
)
from paybond_kit.agent.registry import PaybondToolRegistry, create_paybond_tool_registry
from paybond_kit.agent.run import PaybondAgentRun, PaybondAgentRunFacade
from paybond_kit.agent.types import (
    PaybondAgentRunBindConfig,
    PaybondAgentRunBindError,
    PaybondAuthorizeToolCallInput,
    PaybondEvidenceMapper,
    PaybondRunAgentContext,
    PaybondRunAgentContextInput,
    PaybondRunBinding,
    PaybondRunBindingAttachInput,
    PaybondRunBindingSandboxBootstrapInput,
    PaybondRunConfigHashMaterials,
    PaybondRunSandboxBinding,
    PaybondSideEffectingToolEntry,
    PaybondSideEffectingToolPolicy,
    PaybondSpendResolver,
    PaybondToolCallContext,
    PaybondToolDeniedResolution,
    PaybondToolPassthroughResolution,
    PaybondToolRegistryConfig,
    PaybondToolRegistryValidationError,
    PaybondToolResolution,
    PaybondToolSideEffectingResolution,
    PaybondToolInputGuardAllowDecision,
    PaybondToolInputGuardApprovalRequiredDecision,
    PaybondToolInputGuardDecision,
    PaybondToolInputGuardDenyDecision,
    PaybondTraceSink,
    PaybondUnregisteredSideEffectingToolError,
)

__all__ = [
    "PaybondAgentHooks",
    "PaybondAgentResult",
    "PaybondGenericAgentConfig",
    "CreateGuardedAgentInput",
    "CreateGuardedAgentResult",
    "GuardedAgentFramework",
    "PaybondAgentRunBindError",
    "PaybondAgentRunFacade",
    "PaybondEvidenceMapper",
    "PaybondAuthorizeToolCallInput",
    "PaybondAutoEvidenceSubmitError",
    "PaybondEvidenceSubmitError",
    "PaybondToolDeniedResolution",
    "AgentReceiptComposeResult",
    "PaybondInterceptEvidenceResult",
    "PaybondInterceptWrapExecuteResult",
    "PaybondRunAgentContext",
    "PaybondRunAgentContextInput",
    "PaybondRunBinding",
    "PaybondRunBindingAttachInput",
    "PaybondRunBindingSandboxBootstrapInput",
    "PaybondRunConfigHashMaterials",
    "PaybondRunSandboxBinding",
    "PaybondSideEffectingToolEntry",
    "PaybondSideEffectingToolPolicy",
    "PaybondSpendResolver",
    "PaybondToolCallContext",
    "PaybondToolInputGuardAllowDecision",
    "PaybondToolInputGuardApprovalRequiredDecision",
    "PaybondToolInputGuardDecision",
    "PaybondToolInputGuardDenyDecision",
    "PaybondToolInputGuardAdapter",
    "PaybondToolInterceptor",
    "PaybondToolPassthroughResolution",
    "PaybondToolRegistry",
    "PaybondToolRegistryConfig",
    "PaybondToolRegistryValidationError",
    "PaybondToolResolution",
    "PaybondToolSideEffectingResolution",
    "PaybondTraceSink",
    "PaybondUnregisteredSideEffectingToolError",
    "create_generic_tool_executor",
    "create_guarded_agent",
    "create_guarded_agent_runner",
    "create_paybond_agent",
    "create_paybond_generic_agent_config",
    "create_paybond_generic_input_guard",
    "create_paybond_tool_registry",
    "create_tool_input_guard_adapter",
    "instrument_paybond_agent",
    "paybond_generic_tool_executor_adapter",
    "paybond_tool_input_guard_adapter",
    "resolve_agent_policy_source",
    "to_paybond_agent_result",
    "wrap_paybond_tools",
]
